from PyQt5.QtWidgets import * 
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 610)
        MainWindow.setStyleSheet("background-color: rgb(218, 207, 183);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(170, 200, 160, 311))
        self.gridWidget.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(31, 141, 9);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 0, 1, 1)
        self.lineEdit_Login = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_Login.setStyleSheet("background-color: rgba(255, 255, 255, 126);")
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.gridLayout.addWidget(self.lineEdit_Login, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(154, 2, 2);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(31, 141, 9);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.lineEdit_Pass = QtWidgets.QLineEdit(self.gridWidget)
        self.lineEdit_Pass.setStyleSheet("background-color: rgba(255, 255, 255, 126);")
        self.lineEdit_Pass.setObjectName("lineEdit_Pass")
        self.lineEdit_Pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.gridLayout.addWidget(self.lineEdit_Pass, 3, 0, 1, 1)
        self.label_Password = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")
        self.gridLayout.addWidget(self.label_Password, 2, 0, 1, 1)
        self.label_Login_2 = QtWidgets.QLabel(self.gridWidget)
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_Login_2.setFont(font)
        self.label_Login_2.setObjectName("label_Login_2")
        self.gridLayout.addWidget(self.label_Login_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 40, 181, 61))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 291, 41))
        font = QtGui.QFont()
        font.setFamily("URW Bookman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 570, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(87, 87, 87);")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "guest"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
        self.label_Password.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Password:</span></p></body></html>"))
        self.label_Login_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Login:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>P C M</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "project change management"))
        self.pushButton_4.setText(_translate("MainWindow", "Admin"))
